# See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:

# Sparkle Platform
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "05:00"
    timezone: Australia/Sydney
  reviewers:
    - "sparkletown/engineering-leads"
  open-pull-requests-limit: 2
  target-branch: staging
  versioning-strategy: auto

# Sparkle Platform - Backend Functions
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: weekly
    day: "monday"
    time: "05:00"
    timezone: Australia/Sydney
  reviewers:
    - "sparkletown/engineering-leads"
  open-pull-requests-limit: 2
  target-branch: staging
  versioning-strategy: auto

# Sparkle Platform - Reporting Tools
- package-ecosystem: npm
  directory: "/reporting"
  schedule:
    interval: weekly
    day: "monday"
    time: "05:00"
    timezone: Australia/Sydney
  reviewers:
    - "sparkletown/engineering-leads"
  open-pull-requests-limit: 2
  target-branch: staging
  versioning-strategy: auto
